# Generated by Django 4.2.7 on 2023-11-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0011_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
