# Generated by Django 4.2.7 on 2023-11-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0014_alter_logs_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
