# Generated by Django 4.2.7 on 2023-12-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0015_alter_logs_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='log_date',
            new_name='log_in',
        ),
        migrations.AddField(
            model_name='logs',
            name='log_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
