# Generated by Django 4.2.7 on 2023-12-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0016_rename_log_date_logs_log_in_logs_log_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
