# Generated by Django 4.2.7 on 2023-12-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0017_alter_passwordresettoken_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AddField(
            model_name='userdata',
            name='doctor_id',
            field=models.AutoField(default=888, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
