# Generated by Django 4.2.7 on 2023-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0002_patient_ventilator_assigned_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('PASSIVE', 'Passive'), ('EMERGENCY', 'Emergency')], default='PASSIVE', max_length=20),
        ),
    ]
