# Generated by Django 4.2.7 on 2023-11-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0004_ventilator_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventilator',
            name='assigned_patient',
        ),
    ]
