# Generated by Django 4.2.7 on 2023-11-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0005_remove_ventilator_assigned_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ventilator_staus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
