# Generated by Django 4.2.7 on 2023-11-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0006_ventilator_staus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ventilator_staus',
        ),
        migrations.RemoveField(
            model_name='ventilator',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='ventilator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ventilator',
            name='is_available',
        ),
    ]
