# Generated by Django 4.2.7 on 2023-11-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0007_delete_ventilator_staus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventilator',
            name='status',
            field=models.CharField(choices=[('allocated', 'Allocated'), ('not_allocated', 'Not Allocated')], default='not_allocated', max_length=20),
        ),
    ]
