# Generated by Django 4.2.7 on 2023-12-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0009_alter_ventilator_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ventilator',
            name='status',
            field=models.CharField(choices=[('allocated', 'Allocated'), ('Not allocated', 'Not Allocated')], default='Not allocated', max_length=20),
        ),
    ]
