# Generated by Django 4.2.7 on 2023-12-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0010_userdevices_alter_ventilator_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdevices',
            new_name='mydevices',
        ),
    ]
