# Generated by Django 4.2.7 on 2023-12-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0012_v'),
    ]

    operations = [
        migrations.DeleteModel(
            name='V',
        ),
    ]
