# Generated by Django 4.2.7 on 2023-12-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0013_delete_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydevices',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
