# Generated by Django 4.2.7 on 2023-12-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0015_patient_doc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
