# Generated by Django 4.2.7 on 2023-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0016_remove_patient_id_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
