# Generated by Django 4.2.7 on 2023-12-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0021_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventilator.ventilator'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('PASSIVE', 'Passive'), ('EMERGENCY', 'Emergency'), ('DISCHARGED', 'Discharged')], default='PASSIVE', max_length=20),
        ),
    ]
