# Generated by Django 4.2.7 on 2023-12-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0022_patient_device_alter_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
