# Generated by Django 4.2.7 on 2023-12-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0023_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydevices',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
