# Generated by Django 4.2.7 on 2023-12-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0024_alter_mydevices_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
