# Generated by Django 4.2.7 on 2023-12-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0025_alter_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doc_id',
            field=models.CharField(default=888, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
