# Generated by Django 4.2.7 on 2023-12-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0026_patient_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doc_id',
            field=models.CharField(max_length=255),
        ),
    ]
