# Generated by Django 4.2.7 on 2023-12-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0027_alter_patient_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('device_log_in', models.DateTimeField(blank=True, null=True)),
                ('device_log_out', models.DateTimeField(blank=True, null=True)),
                ('device_log_date', models.DateField(blank=True, null=True)),
                ('assigned_by_doc_id', models.CharField(max_length=255)),
                ('assigned_to_patient_id', models.CharField(max_length=255)),
            ],
        ),
    ]
