# Generated by Django 4.2.7 on 2023-12-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0028_device_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_logs',
            name='device_log_date',
        ),
        migrations.RemoveField(
            model_name='device_logs',
            name='id',
        ),
        migrations.AddField(
            model_name='device_logs',
            name='log_id',
            field=models.AutoField(default=888, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
