# Generated by Django 4.2.7 on 2023-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0029_remove_device_logs_device_log_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_logs',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
