# Generated by Django 4.2.7 on 2023-12-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0030_alter_device_logs_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_logs',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
