# Generated by Django 4.2.7 on 2023-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0032_remove_ventilator_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventilator',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ventilator',
            name='product_id',
        ),
        migrations.AddField(
            model_name='ventilator',
            name='mac',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventilator',
            name='mfg_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
