# Generated by Django 4.2.7 on 2023-12-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilator', '0033_remove_ventilator_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventilator',
            name='battery_mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventilator',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
